table Fact_Gastos
	lineageTag: 1dde9d9f-aeda-488a-bb8c-30909e0d2bf3

	column _id
		dataType: string
		lineageTag: 4d8b6d59-d930-4c70-aa46-6e6061719a05
		summarizeBy: none
		sourceColumn: _id

		annotation SummarizationSetBy = Automatic

	column Ejercicio
		dataType: int64
		formatString: 0
		lineageTag: 0c4a81b5-b10f-471e-9bb5-114fe2c2c5f7
		summarizeBy: none
		sourceColumn: Ejercicio

		annotation SummarizationSetBy = Automatic

	column 'Centro Gestor'
		dataType: string
		lineageTag: cf9b0d8e-fced-4e8c-83d2-62644f9aeb59
		summarizeBy: none
		sourceColumn: Centro Gestor

		annotation SummarizationSetBy = Automatic

	column Funcional
		dataType: string
		lineageTag: b2da4854-e493-4f69-bc72-b9921ad21927
		summarizeBy: none
		sourceColumn: Funcional

		annotation SummarizationSetBy = Automatic

	column Economico
		dataType: string
		lineageTag: a3560b4c-e1c4-49ea-b469-6d5ab53549ed
		summarizeBy: none
		sourceColumn: Economico

		annotation SummarizationSetBy = Automatic

	column Financiacion
		dataType: string
		lineageTag: e6429baf-a2d0-4605-a921-f26015695dd2
		summarizeBy: none
		sourceColumn: Financiacion

		annotation SummarizationSetBy = Automatic

	column Descripcion
		dataType: string
		lineageTag: 45161740-5154-4301-bc20-fd28fa22cc36
		summarizeBy: none
		sourceColumn: Descripcion

		annotation SummarizationSetBy = Automatic

	column 'Credito inicial'
		dataType: double
		lineageTag: 2711b2ca-b3c5-45ac-a38d-7dee3fcf6c24
		summarizeBy: sum
		sourceColumn: Credito inicial

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Modificaciones
		dataType: double
		lineageTag: 5593c7e9-1488-462b-88aa-677949e8de5e
		summarizeBy: sum
		sourceColumn: Modificaciones

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Credito Definitivo'
		dataType: double
		lineageTag: da933b1e-9645-408a-992a-5520dcd16443
		summarizeBy: sum
		sourceColumn: Credito Definitivo

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Comprometido
		dataType: double
		lineageTag: 286e9c47-8415-442e-af4e-a7d3c1868778
		summarizeBy: sum
		sourceColumn: Comprometido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Obligaciones Reconocidas'
		dataType: double
		lineageTag: e329831e-fa7c-424b-a478-0422616c7a93
		summarizeBy: sum
		sourceColumn: Obligaciones Reconocidas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Pagado
		dataType: double
		lineageTag: 4a4c10c7-7eaf-45d1-adbf-b41aeb660466
		summarizeBy: sum
		sourceColumn: Pagado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Fact_Gastos = m
		mode: import
		source =
				let
				    Origen = Table.Combine({#"Estado de ejecución gastos - 2023", #"Estado de ejecución gastos - 2013", #"Estado de ejecución gastos - 2024", #"Estado de ejecución gastos - 2015", #"Estado de ejecución gastos - 2014", #"Estado de ejecución gastos - 2016", #"Estado de ejecución gastos - 2017", #"Estado de ejecución gastos - 2018", #"Estado de ejecución gastos - 2019", #"Estado de ejecución gastos - 2020", #"Estado de ejecución gastos - 2021", #"Estado de ejecución gastos - 2022"}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Ejercicio", type text}}),
				    #"Filas filtradas" = Table.SelectRows(#"Tipo cambiado", each ([Ejercicio] <> "Resultado total")),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Filas filtradas",{{"Ejercicio", Int64.Type}}),
				    #"Filas filtradas1" = Table.SelectRows(#"Tipo cambiado1", each true),
				    #"Filas filtradas2" = Table.SelectRows(#"Filas filtradas1", each [Ejercicio] >= 2013)
				in
				    #"Filas filtradas2"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

