table 'Tabla de Medidas'
	lineageTag: e2864f84-e8ff-4b5d-a36b-a5cdea7cbba9

	measure 'Total Credito Inicial' =
			
			SUM (
			    Fact_Gastos[Credito inicial]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 6bd17ae7-1985-4ac5-9b9e-d402668d19c9

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Modificaciones' =
			
			SUM (
			    Fact_Gastos[Modificaciones]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 656367b7-ce56-4420-8e0a-3de7deb9b864

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Credito Definitivo' =
			
			SUM (
			    Fact_Gastos[Credito Definitivo]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b3f1f69c-f7a7-45ce-a821-c26e20929aa3

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Comprometido' =
			
			SUM (
			    Fact_Gastos[Comprometido]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 12f75144-2a05-44b9-bccc-6df7bd252c91

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Obligaciones Reconocidas' =
			
			SUM (
			    Fact_Gastos[Obligaciones Reconocidas]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2aa72a6c-316b-4789-9410-a05e8ffc517b

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Pagado' =
			
			SUM (
			    Fact_Gastos[Pagado]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: b674d119-2fe3-4ac8-9c58-21d47d163989

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure '% Obligaciones Reconocidas' =
			
			DIVIDE(
			    [Total Obligaciones Reconocidas],
			    [Total Credito Definitivo]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: cf5e6c50-d405-492b-a1d3-81f9533c0bf0

	measure '% Ejecucion' =
			
			DIVIDE(
			    [Total Pagado],
			    [Total Credito Definitivo]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: d29592c3-8e88-4c47-90a0-099df9bb3b20

	measure 'Variacion Presupuestaria' =
			
			[Total Credito Definitivo] - [Total Credito Inicial]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: a1471914-fdba-4e6f-a17c-734d8f91490f

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Prevision Inicial' =
			
			SUM (
			    Fact_Ingresos[Prevision Inicial]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 00b092a4-04fb-4fd4-883c-7cd84ceef437

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Modificaciones Ingresos' =
			
			SUM (
			    Fact_Ingresos[Modificaciones]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: fac1f953-7883-444d-a1a1-fd174003c4a8

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Prevision Definitiva' =
			
			SUM (
			    Fact_Ingresos[Prevision Definitiva]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 886571fd-8d5b-4a8d-b146-24e40a9f62f6

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Derechos Reconocidos Netos' =
			
			SUM (
			    Fact_Ingresos[D. Rec. Netos]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 7b0120be-d6cf-484e-b09f-b5209274b908

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Total Recaudado Neto' =
			
			SUM (
			    Fact_Ingresos[Recaudado Neto]
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 8334479b-de79-484e-9cac-c8a41bb76c71

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure '% Ejecucion Ingresos' =
			
			DIVIDE(
			    [Total Derechos Reconocidos Netos],
			    [Total Prevision Definitiva],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 0640bd44-3653-4c67-baf6-3b1a18c1fbed

	measure '% Recaudacion' =
			
			DIVIDE(
			    [Total Recaudado Neto],
			    [Total Derechos Reconocidos Netos],
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 395cd917-304e-44a3-b5ee-9a1adccafb5e

	measure 'Resultado Presupuestario' =
			
			[Total Derechos Reconocidos Netos] - [Total Obligaciones Reconocidas]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2de6e095-3ae2-4d6a-8da9-257f49042f88

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Capacidad Necesidad Financiacion' =
			
			[Total Recaudado Neto] - [Total Pagado]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: d013fac5-a0e1-4234-826c-90883b16f7e7

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure '% Ejecucion Gasto' =
			
			DIVIDE(
			    [Total Obligaciones Reconocidas],
			    [Total Credito Definitivo]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 0543acf3-feff-46b8-b365-f3f6a902d23f

	measure '% Ejecuion LY' =
			
			CALCULATE(
			    [% Ejecucion],
			    FILTER(
			        ALL(Dim_Ejercicio),
			        Dim_Ejercicio[Ejercicio] = MAX(Dim_Ejercicio[Ejercicio]) - 1
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b9858185-db96-4590-a3a4-523a8d0b75cb

	measure '% Ejecucion Delta LY' =
			
			[% Ejecucion] - [% Ejecuion LY]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: ab4153ae-7384-4a43-8e46-8c56949060fe

	measure '% Ejecucion Delta Target' =
			
			[% Ejecucion] - 1
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7c93c173-dcfa-4085-8d0a-cad1fe3322b2

	measure '% Ejecucion Badge LY' = ```
			
			VAR Delta = [% Ejecucion Delta LY]
			VAR DeltaPct = 
			    FORMAT(Delta, "+0.00%;-0.00%")
			RETURN
			IF(
			    ISBLANK([% Ejecuion LY]),
			    BLANK(),
			    DeltaPct &
			    IF(Delta >= 0, " ▲ ", " ▼ ")
			    --IF(Delta >= 0, " ▲ vs Año Ant.", " ▼ vs Año Ant.")
			)
			```
		lineageTag: 0f88797a-8a6a-4ed7-8417-027dbc4fc2b5

	measure '% Ejecucion Badge Target' =
			
			VAR Delta = [% Ejecucion Delta Target]
			RETURN
			FORMAT(Delta, "+0.00%;-0.00%") &
			IF(Delta >= 0, " ▲ ", " ▼ ")
			--IF(Delta >= 0, " ▲ vs 100%", " ▼ vs 100%")
		lineageTag: 6881e07c-8098-424c-973a-51ac284a9820

	measure 'Delta Obligaciones LY' =
			
			[Total Obligaciones Reconocidas] -
			CALCULATE(
			    [Total Obligaciones Reconocidas],
			    FILTER(
			        ALL(Dim_Ejercicio),
			        Dim_Ejercicio[Ejercicio] = MAX(Dim_Ejercicio[Ejercicio]) - 1
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 1a87bcdd-789c-4c54-b97a-65ef22c3d441

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Delta Monto Target' =
			
			[Total Credito Definitivo] - [Total Pagado]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 19e6d84f-2cfd-4188-8051-16a7bd718f05

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure '% Recaudacion LY' =
			
			CALCULATE(
			    [% Recaudacion],
			    FILTER(
			        ALL(Dim_Ejercicio),
			        Dim_Ejercicio[Ejercicio] = MAX(Dim_Ejercicio[Ejercicio]) - 1
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: b7b19420-79a1-4d06-a0c6-5f5ef6f8ae72

	measure '% Recaudacion Delta Target' = [% Recaudacion] - 1
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 7dd1dab6-a57c-4dbc-8ee4-e12b2bdb2236

	measure '% Recaudacion Delta LY' =
			
			[% Recaudacion] - [% Recaudacion LY]
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: 5b63931b-7a7d-4439-a30e-4bf01a0137c4

	measure '% Recaudacion Badge LY' =
			
			VAR Delta = [% Recaudacion Delta LY]
			VAR DeltaPct =
			    FORMAT(Delta, "+0.00%;-0.00%")
			RETURN
			IF(
			    ISBLANK([% Recaudacion LY]),
			    BLANK(),
			    DeltaPct &
			    IF(Delta >= 0, " ▲ ", " ▼ ")
			)
		lineageTag: fe59eaa5-5a87-49fa-9a22-aecf19a41d07

	measure '% Recaudacion Badge Target' =
			
			VAR Delta = [% Recaudacion Delta Target]
			RETURN
			FORMAT(Delta, "+0.00%;-0.00%") &
			IF(Delta >= 0, " ▲ ", " ▼ ")
		lineageTag: f70d9f70-2e0c-4b09-92bb-634857a7d67c

	measure 'Delta Recaudado LY' =
			
			[Total Recaudado Neto] -
			CALCULATE(
			    [Total Recaudado Neto],
			    FILTER(
			        ALL(Dim_Ejercicio),
			        Dim_Ejercicio[Ejercicio] = MAX(Dim_Ejercicio[Ejercicio]) - 1
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ad3f3b94-1a65-45ed-87fb-4561c17d9441

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Delta Monto Recaudacion Target' =
			
			[Total Derechos Reconocidos Netos] -
			[Total Recaudado Neto]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: bb20c1f5-801c-4179-bf3d-931cc6cba14a

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Resultado Presupuestario LY' =
			
			CALCULATE(
			    [Resultado Presupuestario],
			    FILTER(
			        ALL(Dim_Ejercicio),
			        Dim_Ejercicio[Ejercicio] = MAX(Dim_Ejercicio[Ejercicio]) - 1
			    )
			)
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2945e3ec-8700-4f77-b1a5-bca9f3dcbacb

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Delta Resultado LY' = ```
			
			[Resultado Presupuestario] - 
			[Resultado Presupuestario LY]
			```
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 69399c60-96b1-4d62-bdfe-5a40de871f30

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure '% Resultado Delta LY' =
			
			DIVIDE(
			    [Delta Resultado LY],
			    ABS([Resultado Presupuestario LY]),
			    0
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		lineageTag: f51ae3c2-9b5d-4c72-ac8b-70bc0d02fdd5

	measure 'Resultado Badge LY' =
			
			VAR Delta = [Delta Resultado LY]
			VAR DeltaFmt =
			    FORMAT(
			        Delta,
			        "+#,0,,.00 "" mill.""" &
			        ";-#,0,,.00 "" mill."""
			    )
			RETURN
			IF(
			    ISBLANK([Resultado Presupuestario LY]),
			    BLANK(),
			    DeltaFmt &
			    IF(Delta >= 0, " ▲ ", " ▼ ")
			)
		lineageTag: 9a6cacb3-16a7-4327-ac58-80a9837fc3aa

	measure 'Resultado Presupuestario Target' = 0
		formatString: 0
		lineageTag: 18a3a284-104b-41df-90ce-dd86e42d995d

	measure 'Delta Resultado Target' =
			
			[Resultado Presupuestario]
		lineageTag: b42dbe53-1541-4517-9165-c149bc0131a9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Resultado Badge Target' =
			
			VAR Delta = [Resultado Presupuestario]
			RETURN
			FORMAT(
			    Delta,
			    "+#,0,,.00 "" mill.""" &
			    ";-#,0,,.00 "" mill."""
			) &
			IF(Delta >= 0, " ▲ ", " ▼ ")
		lineageTag: c5a9b457-43b6-4722-bd91-fc181b86d2d8

	measure 'Capacidad Necesidad Financiacion LY' =
			
			CALCULATE(
			    [Capacidad Necesidad Financiacion],
			    FILTER(
			        ALL(Dim_Ejercicio),
			        Dim_Ejercicio[Ejercicio] = MAX(Dim_Ejercicio[Ejercicio]) - 1
			    )
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 49b98dbf-9f0d-470e-8893-d23d9848c902

	measure 'Delta Capacidad LY' =
			
			[Capacidad Necesidad Financiacion] -
			[Capacidad Necesidad Financiacion LY]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: aaa92826-7077-4646-a8ed-c940a9c69330

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Capacidad Badge LY' =
			
			VAR Delta = [Delta Capacidad LY]
			VAR DeltaFmt =
			    FORMAT(Delta / 1000000, "+0.00;-0.00") & " mill."
			RETURN
			IF(
			    ISBLANK([Capacidad Necesidad Financiacion LY]),
			    BLANK(),
			    DeltaFmt &
			    IF(Delta >= 0, " ▲ ", " ▼ ")
			)
		lineageTag: 40a11aad-a6b3-4dcf-8803-0b57e32b3dc6

	measure 'Delta Capacidad Target' =
			
			[Capacidad Necesidad Financiacion]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3a6d5b50-2440-41cb-a58a-a976e11bee9b

		annotation PBI_FormatHint = {"currencyCulture":"es-US"}

	measure 'Capacidad Badge Target' =
			
			VAR Delta = [Capacidad Necesidad Financiacion]
			VAR DeltaFmt =
			    FORMAT(Delta / 1000000, "+0.00;-0.00") & " mill."
			RETURN
			DeltaFmt &
			IF(Delta >= 0, " ▲ ", " ▼ ")
		lineageTag: d1e84332-43b0-46d5-95ac-1a5871ef76cf

	partition 'Tabla de Medidas' = m
		mode: import
		source =
				let
				    Origen = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Columna1 = _t]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(Origen,{{"Columna1", type text}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Columna1"})
				in
				    #"Columnas quitadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

